'use strict';
const app=document.querySelector('#app');
const storage={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);return true;}catch{return false;}}};
let key=storage.get('moca-foodtruck-key'), me=null, publicData=null, busy=false, step=0, mode='signup';
let draft={name:'',occupation:'',access:'checking',preparation:'checking',roadblocks:'',share_name:false,share_occupation:false},check={state:'partial',roadblocks:''};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function freshKey(){const a=new Uint8Array(32);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('');}
function getKey(){if(!key){key=freshKey();storage.set('moca-foodtruck-key',key);}return key;}
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Moca-Request':'1'},body:JSON.stringify(body)}:{});let data;try{data=await response.json();}catch{throw new Error('서버 응답을 읽지 못했어요. 잠시 뒤 다시 시도해 주세요.');}if(!response.ok){const err=new Error(data.error||'잠시 뒤 다시 시도해 주세요.');err.status=response.status;throw err;}return data;}
function error(text){const target=document.querySelector('#error');if(target)target.textContent=text;}
function facts(){const c=publicData.config;return `<div class="facts"><p><strong>언제 만나요</strong>${escape(c.date)}</p><p><strong>어디서 만나요</strong>${escape(c.venue)}</p><p><strong>함께할 인원</strong>최대 ${c.capacity}명</p><p><strong>참가비</strong>${escape(c.fee)}</p></div>`;}
function shell(html){app.innerHTML=html;app.focus({preventScroll:true});}
function home(){const c=publicData.config;shell(`<section class="hero"><img src="/banner.png" alt="Moca's Restaurant With Dots — Run a business with OpenAI Dots. 복슬복슬한 토끼 모카가 민트색 푸드트럭에서 메뉴와 운영 계획을 살펴봐요"><div class="hero-copy"><span class="eyebrow">MOCA × FOODTRUCKBENCH</span><h1>Dots로 레스토랑 경영하기</h1><span class="pill">결과물 공유 · 오프라인</span><p class="lede">메뉴부터 마지막 정산까지.<br>게임 속 30일을 Dots와 운영하고,<br>우리의 판단과 협업을 나눠요.</p><a class="button" href="#signup">${me?'내 신청 수정하기':'같이 운영해 볼래요 →'}</a><p class="subtle">신청은 약 2~3분으로 예상해요.</p></div></section>${facts()}${me?'<div class="saved">이미 신청했어요 — 고칠래요? <a href="#signup">신청 수정</a> · <a href="#checkin">체크인</a></div>':''}<section class="section"><span class="eyebrow">OUR LITTLE EXPERIMENT</span><h2>수익도, 삐끗한 판단도<br>함께 꺼내 보는 자리예요.</h2><p>같은 푸드트럭 시뮬레이션에서 메뉴와 가격을 정하고, 재료를 주문하고, 직원을 운영해요. 어떤 판단을 Dots에 맡기고 언제 사람이 확인할지 직접 경험해 봐요.</p><p>개발자, 디자이너, 사무직 등 누구나 좋아요. 요식업·경영·코딩 경험은 없어도 괜찮아요. Dots와 협업하는 방식, 그리고 업무나 일상에 가져갈 아이디어 한 가지를 찾아봐요.</p><div class="cards"><article class="card"><span class="number">01 · 모이기 전에</span><h3>내 푸드트럭, 30일 운영</h3><p>본인 Dots 계정과 같은 게임 설정으로 시작해요. 게임 속 일주일에 두 번 정도 운영을 점검하고 판단·결과·막힌 점을 기록해요.</p></article><article class="card"><span class="number">02 · 당일에</span><h3>5분 공유 + 2분 질문</h3><p>참여자마다 결과와 기억에 남는 판단을 나눠요. 완주하지 못했거나 손실이 났어도 괜찮아요.</p></article><article class="card"><span class="number">03 · 함께 돌아보기</span><h3>작은 조로 이야기해요</h3><p>도움이 된 협업 방식과 불편했던 점을 나눠요. 수익과 함께 그 결과를 만든 판단도 살펴봐요.</p></article></div><div class="notice">노트북과 본인 Dots 계정을 준비해요. 구독 중이어도 계정에 따라 접속 가능 여부가 달라요. 시작 전에 실제 접속을 확인해요.<br>Dots 이용권·예상 비용: [미정: 공식 조건 확인]<br>FoodTruckBench 실행 방법·공통 설정·시작 시점: [미정: 사전 과제 안내]</div></section><section class="section"><h2>함께할 자리</h2><p>${publicData.count} / ${c.capacity}명 신청 · ${Math.max(0,c.capacity-publicData.count)}자리 남아 있어요.</p><div class="people">${publicData.participants.map(p=>`<span class="person">${escape(p.name)}${p.occupation?' · '+escape(p.occupation):''}</span>`).join('')}</div><p class="subtle">이름과 하는 일은 직접 공개에 동의한 분만 보여요.</p><p class="subtle">신청 마감: ${escape(c.signup_deadline)}<br>체크인 마감: ${escape(c.checkin_deadline)}<br>${escape(c.fee_details)}</p><div class="actions"><a class="button" href="#signup">${me?'신청 수정하기':'신청하기'}</a><a class="button secondary" href="#checkin">준비 상태 체크인</a></div><p><a href="#recover">다른 기기에서 신청했나요? 복구 열쇠로 불러오기</a></p></section>`);}
const questions=[
{title:'어떤 이름으로 만날까요?',hint:'소모임에서 알아볼 수 있는 이름이나 별명을 적어 주세요. 처음 신청하는데 같은 이름이 있다면 구별되는 별명을 써 주세요.',privacy:'기본 비공개 · 마지막 단계에서 동의한 경우에만 안내 페이지에 보여요.',html:()=>`<label for="name">이름 또는 별명</label><input id="name" name="name" maxlength="40" required autocomplete="off" value="${escape(draft.name)}">`,read:()=>draft.name=document.querySelector('#name').value.trim()},
{title:'평소 어떤 일을 하나요?',hint:'직군이나 주로 하는 일을 짧게 알려 주세요. 회사 이름은 적지 않아도 돼요.',privacy:'기본 비공개 · 마지막 단계에서 별도로 동의한 경우에만 이름과 함께 보여요.',html:()=>`<label for="occupation">하는 일</label><input id="occupation" name="occupation" maxlength="80" required value="${escape(draft.occupation)}">`,read:()=>draft.occupation=document.querySelector('#occupation').value.trim()},
{title:'본인 계정에서 Dots에 접속해 봤나요?',hint:'구독 중이어도 계정에 따라 달라요. 아직 확인하지 않았거나 막혀 있어도 현재 상태를 알려 주세요.',privacy:'비공개 · 진행 준비용으로만 사용해요.',html:()=>select('access',draft.access,[['checking','아직 확인 중이에요'],['ready','실제 접속을 확인했어요'],['blocked','접속에 막힌 점이 있어요']]),read:()=>draft.access=document.querySelector('#access').value},
{title:'사전 과제를 준비할 수 있나요?',hint:'노트북과 본인 Dots 계정으로 FoodTruckBench의 게임 속 30일을 진행해요. 같은 설정으로 시작해 게임 속 일주일에 두 번 정도 운영을 점검하고, 결과·판단·막힌 점을 정리해요. 실행 방법과 시작 시점은 미정이에요.',privacy:'비공개 · 진행 준비용으로만 사용해요.',html:()=>select('preparation',draft.preparation,[['checking','준비 조건을 확인하고 있어요'],['yes','안내를 확인한 뒤 준비할 수 있어요']]),read:()=>draft.preparation=document.querySelector('#preparation').value},
{title:'준비하면서 걸리는 점이 있나요?',hint:'선택 질문이에요. 접속이나 준비에서 막힌 부분만 짧게 적어 주세요. 비밀번호, 연락처, 개인·회사 민감정보는 적지 마세요.',privacy:'비공개 · 진행 준비용으로만 사용해요.',html:()=>`<label for="roadblocks">막힌 점 (선택)</label><textarea id="roadblocks" maxlength="500">${escape(draft.roadblocks)}</textarea>`,read:()=>draft.roadblocks=document.querySelector('#roadblocks').value.trim()},
{title:'안내 페이지에 무엇을 공개할까요?',hint:'공개하지 않아도 신청할 수 있어요. 나중에 수정해서 공개를 취소할 수도 있어요.',privacy:'선택한 항목만 공개 · 나머지 준비 답변과 체크인은 항상 비공개예요.',html:()=>`<label class="option"><input id="share_name" type="checkbox" ${draft.share_name?'checked':''}>이름·별명을 안내 페이지에 공개하는 데 동의해요.</label><label class="option"><input id="share_occupation" type="checkbox" ${draft.share_occupation?'checked':''}>이름과 함께 하는 일도 공개하는 데 동의해요.</label><p class="subtle">신청 정보는 행사 준비를 위해 운영자가 확인해요. 보관 기간·삭제 요청 방법은 [미정: 운영 안내]예요.</p>`,read:()=>{draft.share_name=document.querySelector('#share_name').checked;draft.share_occupation=draft.share_name&&document.querySelector('#share_occupation').checked;}}
];
function select(id,val,options){return `<label for="${id}">현재 상태</label><select id="${id}">${options.map(([v,t])=>`<option value="${v}" ${v===val?'selected':''}>${t}</option>`).join('')}</select>`;}
const checks=[{title:'지금 사전 과제는 어디까지 했나요?',hint:'완주하지 못했어도 괜찮아요. 준비한 결과와 기억에 남는 판단을 5분 동안 나눌 수 있는지 돌아봐 주세요.',privacy:'비공개 · 진행 준비용으로만 사용해요.',html:()=>select('state',check.state,[['partial','진행 중이거나 일부 준비했어요'],['done','결과와 공유할 이야기를 준비했어요'],['not_started','아직 시작하지 못했어요']]),read:()=>check.state=document.querySelector('#state').value},{title:'마지막으로 막힌 점을 알려 주세요.',hint:'선택 질문이에요. 민감정보 없이, 함께 알아두면 좋을 준비 상황만 적어 주세요.',privacy:'비공개 · 진행 준비용으로만 사용해요.',html:()=>`<label for="roadblocks">막힌 점 (선택)</label><textarea id="roadblocks" maxlength="500">${escape(check.roadblocks)}</textarea>`,read:()=>check.roadblocks=document.querySelector('#roadblocks').value.trim()}];
function drawForm(){const qs=mode==='signup'?questions:checks,q=qs[step];shell(`<section class="sheet"><a href="#home">← 활동 안내</a><p class="stepbar"><span>${mode==='signup'?'신청 · 약 2~3분 예상':'체크인 · 약 1분 예상'}</span><span>${step+1} / ${qs.length}</span></p><progress max="${qs.length}" value="${step+1}" aria-label="질문 진행률"></progress>${me&&mode==='signup'?'<p class="saved">이미 신청했어요 — 기존 답변을 고치고 있어요.</p>':''}<h1>${q.title}</h1><p>${q.hint}</p><p class="visibility">${q.privacy}</p><form id="flow">${q.html()}<div id="error" class="error" role="alert"></div><div class="actions">${step?'<button type="button" class="secondary" id="back">이전</button>':''}<button type="submit" id="next">${step===qs.length-1?(mode==='signup'?'신청 저장하기':'체크인 저장하기'):'다음 →'}</button></div></form><p class="subtle">제출 전 답변은 이 페이지 안에만 있어요. 새로고침하면 저장 전 수정 내용은 사라져요. 제출한 답변은 신청 열쇠로 다시 불러올 수 있어요.</p></section>`);document.querySelector('#flow').onsubmit=async e=>{e.preventDefault();if(busy)return;q.read();if(step<qs.length-1){step++;drawForm();return;}busy=true;const submissionHash=location.hash;document.querySelectorAll('#flow button').forEach(b=>b.disabled=true);try{const result=await api(mode==='signup'?'/api/signup':'/api/checkin',{key:getKey(),...(mode==='signup'?draft:check)});me=result.registration;publicData=await api('/api/public');if(location.hash===submissionHash)location.hash='thanks';}catch(e){error(e.message||'연결을 확인하고 다시 시도해 주세요.');}finally{busy=false;document.querySelectorAll('#flow button').forEach(b=>b.disabled=false);}};const back=document.querySelector('#back');if(back)back.onclick=()=>{q.read();step--;drawForm();};}
function recover(){shell(`<section class="sheet"><a href="#home">← 활동 안내</a><h1>신청 열쇠로 다시 만나요.</h1><p>신청할 때 저장한 64자리 복구 열쇠를 붙여 넣어 주세요. 이름만으로는 다른 사람의 답변을 열거나 바꿀 수 없어요.</p><p class="visibility">비공개 · 본인 신청을 불러오는 데만 사용해요. 열쇠를 다른 사람에게 공유하지 마세요.</p><form id="recover"><label for="recovery">복구 열쇠</label><input id="recovery" required minlength="64" maxlength="64" autocomplete="off" spellcheck="false"><div id="error" role="alert" class="error"></div><div class="actions"><button>내 신청 불러오기</button></div></form><p class="subtle">열쇠가 없다면 신청한 기기·브라우저로 돌아가 주세요. 브라우저 데이터를 지우거나 열쇠를 잃으면 여기서 자동 복구할 수 없어요. [미정: 운영자 확인을 통한 복구 방법]</p></section>`);document.querySelector('#recover').onsubmit=async e=>{e.preventDefault();if(busy){error('저장 중이에요. 잠시 뒤 다시 시도해 주세요.');return;}busy=true;const recoveryHash=location.hash;const button=e.target.querySelector('button');button.disabled=true;try{const candidate=document.querySelector('#recovery').value.trim();const result=await api('/api/me',{key:candidate});key=candidate;storage.set('moca-foodtruck-key',key);me=result.registration;if(location.hash===recoveryHash)location.hash='signup';}catch(e){error(e.message||'다시 시도해 주세요.');}finally{busy=false;button.disabled=false;}};}
function thanks(){const c=publicData.config;if(!me){location.hash='home';return;}shell(`<section class="sheet"><span class="eyebrow">SAVED · 잘 도착했어요</span><h1>함께할 준비,<br>고마워요!</h1><p>${escape(me.name)} 님의 신청 정보가 저장되어 있어요. 한 자리로 유지돼요.${me.checkin?' 체크인도 저장되어 있어요.':''}</p>${facts()}<p class="subtle">${escape(c.fee_details)}<br>체크인 마감: ${escape(c.checkin_deadline)}</p><h2>만날 곳</h2><p id="address">${escape(c.address||c.venue)}</p><button id="copy-address" class="secondary" ${c.address?'':'disabled'}>주소 복사</button>${!c.address?'<p class="subtle">정확한 주소가 정해지면 복사할 수 있어요.</p>':''}<h2>복구 열쇠를 챙겨 주세요.</h2><p class="subtle">브라우저 저장이 허용되어 있으면 같은 브라우저는 신청을 기억해요. 저장이 차단되거나 다른 기기에서 수정·체크인하려면 이 열쇠가 필요해요. 열쇠를 가진 사람은 답변을 읽고 바꿀 수 있으니 개인적으로 보관해 주세요.</p><p class="key" id="key">${escape(key)}</p><button id="copy-key" class="secondary">복구 열쇠 복사</button><p id="copy-status" role="status"></p><div class="actions"><a class="button" href="#checkin">체크인하기</a><a class="button secondary" href="#home">활동 안내로</a></div><p><a href="#signup">신청 수정하기</a></p></section>`);document.querySelector('#copy-key').onclick=()=>copy(key);document.querySelector('#copy-address').onclick=()=>copy(c.address);}
async function copy(text){try{await navigator.clipboard.writeText(text);document.querySelector('#copy-status').textContent='복사했어요.';}catch{document.querySelector('#copy-status').textContent='자동 복사가 어려워요. 위 텍스트를 길게 눌러 복사해 주세요.';}}
function route(){if(!publicData)return;const hash=location.hash.slice(1)||'home';if(hash==='recover')return recover();if(hash==='thanks')return thanks();if(hash==='signup'||hash==='checkin'){mode=hash;step=0;if(hash==='checkin'&&!me){shell('<section class="sheet"><h1>먼저 신청을 불러와 주세요.</h1><p>체크인은 이미 신청한 분만 할 수 있어요. 신청한 브라우저를 사용하거나 복구 열쇠로 불러와 주세요.</p><div class="actions"><a class="button" href="#recover">신청 불러오기</a><a class="button secondary" href="#signup">처음 신청하기</a></div></section>');return;}if(me){draft={...me};check=me.checkin?{...me.checkin}:{state:'partial',roadblocks:''};}return drawForm();}home();}
async function init(){try{publicData=await api('/api/public');if(key){try{me=(await api('/api/me',{key})).registration;}catch(e){if(e.status!==404&&e.status!==401)throw e;}}route();}catch{shell('<section class="sheet"><h1>잠깐, 연결을 확인해 주세요.</h1><p>신청 정보를 불러오지 못했어요. 로컬 미리보기라면 Python 서버가 실행 중인지 확인해 주세요.</p><button id="retry">다시 불러오기</button></section>');document.querySelector('#retry').onclick=init;}}
window.addEventListener('hashchange',route);init();
